spring:
  profiles:
    active: TSYS
  jpa:
    show-sql: true
  datasource:
    driverClassName: "oracle.jdbc.driver.OracleDriver"
    url: "jdbc:oracle:thin:@ldap://tnsds.discoverfinancial.com:3090/q_fiat_qtsys,cn=OracleContext,dc=discoverfinancial,dc=com"

management:
  security:
    enabled: false
 

        